server:
  port: 8003
  servlet:
    context-path: /storage
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

spring:
  application:
    name: zhiran-storage-server
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.88.130:3305/zhiranAI?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: password
    initialSize: 10
    minIdle: 20
    maxActive: 100
    maxWait: 60000
  cloud:
    nacos:
      server-addr: 192.168.88.130:8848
  redis:
    port: 6379
    host: 192.168.88.130
    jedis:
      pool:
        max-active: 8
        max-wait: 1000
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 1000
  rabbitmq:
    host: 192.168.88.130
    port: 5672
    username: root
    password: password
    virtual-host: /zhiranAI
logging:
  level:
    org.springframework: DEBUG

